### ISSUE TITLE
what means aboudt 「AUTH_TOKEN」？

### ISSUE THREAD

**Issue by duyananbryce** [keigoh4315/ticktick-to-notion#1]
i am not programer，i cannot understand about AUTH_TOKEN,is that means
cookie or some thing like key staff,if you can tell me,i will veryappreciate

**Comment by keigoh4315** [comment]
Thanks for contacting.
AUTH_TOKEN is a string for authentication.
It is used to verify if the request from IFTTT is your own.
Please set up any string you like in both IFTTT and GAS. UUID or similar token seem to be a good choice.

**Comment by duyananbryce** [comment]
Oh ！I konw，i will try it later，very thank you
2022年8月31日 +0800 PM5:21 keigoh4315 ***@***.***>，写道：
